language: python
python:
  - 2.7

services:
  - memcached

install:
  - sudo npm install -g coffee-script
  - pip install -r dev-requirements.txt

script: coverage run setup.py -q nosetests

after_success: coveralls
