"""empty message

Revision ID: 2898439357ba
Revises: 29b9ba043f36
Create Date: 2014-04-11 13:42:22.741284

"""

# revision identifiers, used by Alembic.
revision = '2898439357ba'
down_revision = '29b9ba043f36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('email_verify_code', sa.CHAR(length=32), nullable=True))
    op.create_index('ix_user_email_verified', 'user', ['email_verified'], unique=False)
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['email_verify_code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user')
    op.drop_constraint(None, 'user')
    op.drop_index('ix_user_email_verified', table_name='user')
    op.drop_column('user', 'email_verify_code')
    op.drop_column('user', 'email_verified')
    op.drop_column('user', 'email')
    ### end Alembic commands ###
