"""empty message

Revision ID: 29b9ba043f36
Revises: 2a050ba2cf5
Create Date: 2014-04-07 13:34:23.072394

"""

# revision identifiers, used by Alembic.
revision = '29b9ba043f36'
down_revision = '2a050ba2cf5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
