"""empty message

Revision ID: 2a050ba2cf5
Revises: None
Create Date: 2014-04-06 22:36:56.791790

"""

# revision identifiers, used by Alembic.
revision = '2a050ba2cf5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
