"""empty message

Revision ID: 32c4a5ffdcd0
Revises: 378bf88445c8
Create Date: 2014-04-15 21:48:37.776400

"""

# revision identifiers, used by Alembic.
revision = '32c4a5ffdcd0'
down_revision = '378bf88445c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('content_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'content_html')
    ### end Alembic commands ###
