"""empty message

Revision ID: 34cd82a3586c
Revises: None
Create Date: 2014-03-22 21:13:13.136172

"""

# revision identifiers, used by Alembic.
revision = '34cd82a3586c'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('douban_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('douban_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('large_avatar', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('signature', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('desc', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('douban_uid', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('douban_alt', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('douban_access_token', mysql.CHAR(length=32), nullable=False),
    sa.Column('douban_refresh_token', mysql.CHAR(length=32), nullable=False),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('douban_expires_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('evernote_username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('evernote_access_token', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('is_i18n', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('enable_sync', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('book',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('douban_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('evernote_guid', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('cover', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('pubdate', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('summary', mysql.TEXT(), nullable=True),
    sa.Column('enable_sync', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('updated', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
