"""empty message

Revision ID: 378bf88445c8
Revises: 2898439357ba
Create Date: 2014-04-15 13:30:05.412233

"""

# revision identifiers, used by Alembic.
revision = '378bf88445c8'
down_revision = '2898439357ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('template', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'template')
    ### end Alembic commands ###
