"""empty message

Revision ID: 3d4a9633358d
Revises: None
Create Date: 2014-04-21 14:09:35.111719

"""

# revision identifiers, used by Alembic.
revision = '3d4a9633358d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
