"""empty message

Revision ID: 6f5f1aa4134
Revises: None
Create Date: 2014-04-01 19:06:11.855106

"""

# revision identifiers, used by Alembic.
revision = '6f5f1aa4134'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('douban_name', sa.String(length=50), nullable=False),
    sa.Column('douban_id', sa.String(length=20), nullable=False),
    sa.Column('large_avatar', sa.String(length=200), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('signature', sa.String(length=500), nullable=True),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.Column('douban_uid', sa.String(length=20), nullable=False),
    sa.Column('douban_alt', sa.String(length=200), nullable=True),
    sa.Column('douban_access_token', sa.CHAR(length=32), nullable=False),
    sa.Column('douban_refresh_token', sa.CHAR(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('douban_expires_at', sa.Integer(), nullable=True),
    sa.Column('evernote_username', sa.String(length=50), nullable=True),
    sa.Column('evernote_access_token', sa.String(length=200), nullable=True),
    sa.Column('evernote_notebook', sa.String(length=36), nullable=True),
    sa.Column('is_i18n', sa.Boolean(), nullable=True),
    sa.Column('enable_sync', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('douban_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('evernote_guid', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('cover', sa.String(length=200), nullable=True),
    sa.Column('pubdate', sa.String(length=10), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('enable_sync', sa.Boolean(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.drop_table('user')
    ### end Alembic commands ###
